# Generated by Django 4.2.13 on 2024-07-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynotify', '0009_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotificationtemplate',
            name='locale',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotificationtemplate',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='adminnotificationtemplate',
            unique_together={('slug', 'locale')},
        ),
    ]
